#!/bin/sh
# devtmpfs does not get automounted for initramfs
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
#
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
# 
echo "INITRD STARTING..."
/bin/mkdir /mnt/new_root
/bin/mount /dev/mmcblk0p2 /mnt/new_root/
#
echo "SWITCHING ROOT..."
cd /mnt/new_root
/bin/mount --move /sys /mnt/new_root/sys
/bin/mount --move /proc /mnt/new_root/proc
/bin/mount --move /dev /mnt/new_root/dev
echo "LIST /new_root/dev"
ls -la /mnt/new_root/dev
exec /sbin/switch_root -c /dev/console /mnt/new_root linuxrc
#
echo "Dropping to Shell..."
exec /sbin/init $*
